// Biohacking Codex Data - Centralized Repository
const codexData = {
    'ache': 'Acetylcholinesterase: An enzyme that breaks down acetylcholine. Inhibiting this (e.g. with Huperzine-A) increases neuro-connectivity.',
    'alpha gpc': 'A high-bioavailability choline source that crosses the blood-brain barrier, essential for memory and cognitive fluidity.',
    'amygdala': 'The brain\'s emotional processing hub. Responsible for the "fight or flight" response and emotional memory. Targeted by adaptogens like Ashwagandha to modulate stress.',
    'ashwagandha': 'An adaptogenic herb that helps the body manage stress by down-regulating cortisol levels.',
    'autophagy': 'The body\'s way of cleaning out damaged cells, in order to regenerate newer, healthier cells.',
    'bdnf': 'Brain-Derived Neurotrophic Factor: A protein that supports the survival of existing neurons and encourages the growth of new ones.',
    'binaural beats': 'An auditory illusion created by playing two slightly different frequencies in each ear, used for brainwave entrainment.',
    'cerebellum': 'Coordinates voluntary movements such as posture, balance, coordination, and speech, resulting in smooth and balanced muscular activity. Key to physical "Flow State".',
    'coq10': 'Coenzyme Q10: A mitochondrial catalyst that supports cellular energy production. Works synergistically with PQQ.',
    'choline': 'A precursor to acetylcholine, essential for memory, mood, and muscle control.',
    'gaba': 'Gamma-Aminobutyric Acid: The primary inhibitory neurotransmitter in the CNS, crucial for reducing neuronal excitability and promoting relaxation.',
    'glycine': 'An amino acid that acts as a neurotransmitter, improving sleep quality and lowering core body temperature.',
    'hippocampus': 'A major component of the human brain, crucial for the consolidation of information from short-term memory to long-term memory. Optimized by Bacopa and Lion\'s Mane.',
    'hrv': 'Heart Rate Variability: The variation in time between heartbeats. A higher HRV typically indicates better recovery and nervous system balance.',
    'huperzine': 'A potent AChE inhibitor that prevents the breakdown of acetylcholine, often used in lucid dreaming protocols.',
    'kratom': 'A botanical resource containing alkaloids like mitragynine. Investigated for its role in stress modulation and resilience.',
    'l-theanine': 'An amino acid found in tea that promotes relaxation without drowsiness, often stacked with caffeine for "calm focus".',
    'lion\'s mane': 'A medicinal mushroom known for its neuroprotective properties and ability to stimulate Nerve Growth Factor (NGF).',
    'mag-threonate': 'Magnesium L-Threonate: A highly bioavailable form of magnesium that effectively crosses the blood-brain barrier to support synapse density and cognitive function.',
    'nac': 'N-Acetyl Cysteine: A precursor to glutathione, the body\'s master antioxidant. Essential for detoxification and immune support.',
    'nattokinase': 'A fibrinolytic enzyme derived from Natto that supports healthy blood flow and cardiovascular integrity.',
    'nootropic': 'Compounds that enhance cognitive function, particularly executive functions, memory, creativity, or motivation.',
    'pineal gland': 'A small endocrine gland that produces melatonin, a serotonin-derived hormone which modulates sleep patterns and circadian rhythms.',
    'pqq': 'Pyrroloquinoline Quinone: A redox cofactor that promotes mitochondrial biogenesis and supports cognitive longevity.',
    'prefrontal cortex': 'The brain region responsible for complex cognitive behavior, personality expression, decision making, and moderating social behavior.',
    'rem': 'Rapid Eye Movement: The sleep stage associated with vivid dreaming and memory consolidation.',
    'thalamus': 'A relay station for sensory information, crucial for motor control and sleep/wake cycles.',
    'turkey-tail': 'Turkey Tail Mushroom: A medicinal mushroom rich in polysaccharopeptides (PSP/PSK) that modulates the immune response and supports the microbiome.',
    'uridine': 'A nucleotide that supports synaptic plasticity and works synergistically with choline for brain health.',
    'd3-k2': 'Vitamin D3 + K2: A foundational vitamin synergy required for bone health, immune optimization, and cardiovascular resilience.',
    'vagus nerve': 'The main component of the parasympathetic nervous system, responsible for the "rest and digest" state.',
    'yuschak': 'The gold-standard protocol for lucidity involving specific supplement timing during the WBTB window.'
};
